[package]
name = "grass-rendering"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
gpu-allocator = "0.28.0"
bevy_app = "0.18.1"
bevy_ecs = "0.18.1"
bytemuck = "1.25.0"
glam = { version = "0.32.1", features = ["bytemuck", "mint"] }
gltf = { version = "1.4.1", features = ["utils"] }
itertools = "0.14.0"
raw-window-handle = "0.6.2"
tobj = "4.0.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
winit = { version = "0.30.13", features = ["rwh_06"] }
presser = "0.3.1"
bevy_time = "0.18.1"
dolly = "0.6.0"
image = { version = "0.25.10", features = ["jpeg"] }
thiserror = "2.0.18"
anyhow = "1.0.102"
crossbeam-channel = "0.5.15"
